Repository fourkitchens/sous-drupal-project, pull requests merged in 2022-12, with the labels that each got.

#76 fix: php version update and rename master to main
  .gitignore
  README.md
Labels: Passes Code Review

#78 fix: update node orb
  .circleci/config.yml
Labels: Passes Code Review

#77 Add database password instructions
  README.md
Labels: documentation, Passes Code Review, Passed Functional Review

#67 fix: distro version and find-and-replace command for linux
  composer.json
  sous/Starter.php
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge
