Repository fourkitchens/sous-drupal-project, pull requests merged in 2023-04, with the labels that each got.

#92 Settings scaffold
  assets/scaffold/files/additions-default.settings.txt
  assets/scaffold/files/additions-example.settings.local.txt
  composer.json
Labels: 👍 Ready for Review

#94 Cleanup of Gin Theme integration PR
  config/default/core.extension.yml
  config/default/gin.settings.yml
  sous/Starter.php
Labels: 👍 Ready for Review

#93 remove profile: set gin as administration theme
  composer.json
  config/default/block.block.claro_breadcrumbs.yml
  config/default/block.block.claro_content.yml
  config/default/block.block.claro_local_actions.yml
  config/default/block.block.claro_messages.yml
  config/default/block.block.claro_page_title.yml
  config/default/block.block.claro_primary_local_tasks.yml
  config/default/block.block.claro_secondary_local_tasks.yml
  config/default/block.block.gin_breadcrumbs.yml
  config/default/block.block.gin_content.yml
  config/default/block.block.gin_local_actions.yml
  config/default/block.block.gin_messages.yml
  config/default/block.block.gin_page_title.yml
  config/default/block.block.gin_primary_local_tasks.yml
  config/default/block.block.gin_secondary_local_tasks.yml
  config/default/claro.settings.yml
  config/default/core.extension.yml
  config/default/gin.settings.yml
  config/default/linkit.linkit_profile.default.yml
  config/default/node.settings.yml
  config/default/system.theme.yml
  config/default/views.view.login_history.yml
  config/default/views.view.redirect.yml
  sous/Starter.php
Labels: 🎉 Passes Functional Review

#95 Simplify project setup and dependencies
  .lando.yml
  composer.json
  config/default/core.extension.yml
  config/default/crop.type.focal_point.yml
  config/default/editor.editor.basic_html.yml
  config/default/editor.editor.full_html.yml
  config/default/editor.editor.restricted_html.yml
  config/default/filter.format.basic_html.yml
  config/default/filter.format.full_html.yml
  config/default/filter.format.plain_text.yml
  config/default/filter.format.restricted_html.yml
  config/default/focal_point.settings.yml
  config/default/system.action.user_add_role_action.superuser.yml
  config/default/system.action.user_remove_role_action.superuser.yml
  config/default/user.role.superuser.yml
  package-lock.json
  package.json
  scripts/sous/confex.sh
  scripts/sous/confim.sh
  scripts/sous/import-data.sh
  scripts/sous/local-data-bak.sh
  scripts/sous/rebuild.sh
  scripts/sous/setup.sh
  scripts/sous/theme-build.sh
  scripts/sous/theme-watch.sh
  sous/Starter.php
Labels: 🎉 Ready to Merge

#99 docs: Remove node requirement and additional install steps
  README.md
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review
